function Q = identify_sequences(fname,tc,sl,num_shuffle,ns,min_num_reps,min_distance,ts,save_f)
% This function helps to detect sequences of 'events' in an input file 
% (specifics are below). A sequence is a multi-step series of events (for example, spikes) where 
% individual events repeatedly occur in a specific temporal order, each
% within a specific time window of the preceding event. Of course, any
% series of events could be a sequence with this definition.  The function 
% reports sequences as potentially relevant entities if their occurrence is
% more common than a certain percentage (for example 95% or 99%) of the 
% occurrence of the same sequence in a cohort of shuffled representation of
% the data. Two other criteria need to be fulfilled before a sequence is 
% reported: one is that the sequence needs to repeat itself a certain 
% number of times (for examples 4 or 6 times), and the second is that 
% individual sequence repetitions need to be separated by a specific 
% minimal time window (to avoid overlapping recurrences, or false 
% detections of repetitions within bursts of activity). This function 
% was developed for the analysis of calcium event records generated by 
% Inscopix software.
%
% This function was developed for the following publication: 
% Martel A-C, Pittard D, Devergnas A, Risk B, Nassi JJ, Yu W, Downer JD, 
% Wichmann T, Galvan A. Microendoscopic calcium imaging in supplementary 
% motor area and primary motor cortex of rhesus macaques at rest and during
% arm movement. bioRxiv. 2024:2024.06.20.599918. doi: 10.1101/2024.06.20.599918.
%
% Command line parameters:
%
% fname: name of the spike-resolved imaging file.
% 
% tc_series: time window for analysis (e.g., a variable of [0.05 2] would
% mean that events have to fall into a time window starting 50 ms after the
% event and end 2 s after the event, to be considered part of a sequence. The
% routine can also be used to evaluate correlated activity, choosing a very
% narrow time window (e.g., -0.1 0.1).
%
% sl: sequence lengths vector (e.g. [3 4] means that only sequences of 
% length 3 and 4 are evaluated). 
% 
% num_shuffle: number of Monte Carlo shuffles that will be used for statistics
% 
% ns: percentile score that is being used for comparisons. Note that
% only positive ns values are defined, and that all percentiles are 
% expressed as fractions (e.g. 0.95 means that percentiles >95% are 
% accepted). 
% 
% Min_num_reps: number of repetitions of the sequence that must exist in
% the data file for the identified sequence to be included. For example,
% min_num_reps == 4 would mean that 4 or more repetitions must be in the
% file before it will be recognized as a 'sequence'.
%
% min_distance: minimal temporal distance between consecutive repetitions
% of the sequence (in s).
%
% ts: time slice within the input file (fname) the user is interested in 
% ([100 300] would indicate that the period from 100s to 300s should be 
% investigated). 
% 
% The flag 'save_f' can be 1 or 0.  If set to
% 1, the results are saved in a file based on the root of the file name of
% the input file (with an appended '_seq_multi.mat').
% 
% Output parameters (all contained in output structure Q):
%
% Primary output data:
%
% Q.data:   input data
% Q.metadata:  metadata
% Q.sequences:  sequence information
% Q.sequence_times: sequence timing information
%
% Output data derived from sequence/timing information:
%
% Q.sequences_stat.number_sequence: total number of unique sequences that were detected
%
% Q.sequences_stat.sequence_event_separation.mean:  average temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.sd:    standard deviation of temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.cv:    CV of temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.median:    median temporal distance between events within the sequence
% Q.sequences_stat.sequence_event_separation.iqr:   inter-quartile range of temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.mean_mean_event_separation:    average across all average temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.mean_sd_event_separation:   average across all standard deviations of temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.mean_cv_event_separation: average across all CVs of temporal distances between events within the sequence
% Q.sequences_stat.sequence_event_separation.median_median_event_separation: median of all median temporal distance between events within the sequence
% Q.sequences_stat.sequence_event_separation.median_iqr_event_separation:   median of all inter-quartile ranges of temporal distances between events within the sequence
% 
% Q.sequences_stat.sequence_start_separation.mean:  average temporal distances between start of sequences
% Q.sequences_stat.sequence_start_separation.sd:    standard deviation of temporal distances between starts of the sequence
% Q.sequences_stat.sequence_start_separation.cv:    CV of temporal distances between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.median:    median temporal distance between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.iqr:   inter-quartile range of temporal distances between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.mean_mean_start_separation:    average across all average temporal distances between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.mean_sd_start_separation:  average across all standard deviations of temporal distances between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.mean_cv_start_separation:  average across all CVs of temporal distances between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.median_median_start_separation:    median of all median temporal distance between recurrences of sequences
% Q.sequences_stat.sequence_start_separation.median_iqr_start_separation:   median of all inter-quartile ranges of temporal distances between recurrences of sequences
%
% Q.sequences_stat.sequence_length.shortest:    shortest detected sequence length (in terms of number of elements in sequence)
% Q.sequences_stat.sequence_length.longest: longest detected sequence length (in terms of number of elements in sequence)
% Q.sequences_stat.sequence_length.mean:    mean sequence length (in terms of number of element in sequence)
% Q.sequences_stat.sequence_length.sd:  SD of average length
% Q.sequences_stat.sequence_length.median:  median length of sequences (in terms of number of elements in sequence)    
% Q.sequences_stat.sequence_length.iqr: inter-quartile range of length of sequences (in terms of number of elements in sequences)
% 
% Q.sequences_stat.sequence_repetition.fewest:  minimal number of repetitions of sequences
% Q.sequences_stat.sequence_repetition.most:    maximal number of repetition of sequences
% Q.sequences_stat.sequence_repetition.mean:    mean number of repetition of sequences
% Q.sequences_stat.sequence_repetition.sd:  SD of number of repetition of sequences
% Q.sequences_stat.sequence_repetition.median:  median number of repetition of sequences
% Q.sequences_stat.sequence_repetition.iqr: inter-quartile range of number of repetition of sequences
% 
% Q.sequences_stat.sequence_duration.parametric.shortest:   minimal average duration of sequences
% Q.sequences_stat.sequence_duration.parametric.longest:    maximal average duration of sequences
% Q.sequences_stat.sequence_duration.parametric.mean:   average of average durations of sequences
% Q.sequences_stat.sequence_duration.parametric.sd: SD of average durations of sequences
% Q.sequences_stat.sequence_duration.non_parametric.shortest:   shortest median duration of sequences    
% Q.sequences_stat.sequence_duration.non_parametric.longest:    longest median duration of sequences    
% Q.sequences_stat.sequence_duration.non_parametric.median: median of median durations of sequences
% Q.sequences_stat.sequence_duration.non_parametric.iqr:    inter-quartile range of median durations of sequences
% 
% Q.sequences_stat.sequence_index.individual:   index based on INDIVIDUAL sequences: (length * number of repetitions)/time slice length
% Q.sequences_stat.sequence_index.global.parametric:    index based on ALL detected sequences (number of sequences * average length of sequences * average number of repetitions)/(average time slice duration) 
% Q.sequences_stat.sequence_index.global.non_parametric:    non_parametric version of previous line
% Q.sequences_stat.sequence_index2.individual:  set of statistics on the number of spikes for each cell that were engaged in sequences
% Q.sequences_stat.sequence_index2.global:  proportion of all spikes (across entire recording session) that were engaged in sequences
%
% Written 1/9-24/2024, TW

% Execute find_sequences_v25 routine 

R = find_sequences_v25(fname,tc,sl,min_distance,num_shuffle,ns,min_num_reps,ts,0);
% load R_test;

Q.data = R.data;                                % input data
Q.metadata = R.metadata;                        % file metadata
Q.metadata.time_slice = diff(tc);               % duration of time slice

% Summarize results
S = R.sequences;                                % S is the information about sequences (identifying those cells that engage in a given sequence)
T = R.sequence_times;                           % T is the information about occurrence times of the first event of sequences

% convert S into sorted array SA that contains unique sequences

% initialize SA2
ls = zeros(size(S,2),1);
ns = ls;
for i = 1:size(S,2)
    ns(i) = size(S{i},1);        % number of sequences detected
    ls(i) = size(S{i},2);        % length of sequences detected
end
SA2 = zeros(max(ns),max(ls));
m = 0;
for i = 1:size(S,2)
    SA2(m+1:m + size(S{i},1),1:size(S{i},2)) = S{i};
    m = m + size(S{i},1);
end

[SA,~,ind] = unique(SA2,'rows');

% generate TA2, a sorted version of T.  This uses the indices of valid SA
% values (ind) to generate the TA structure.  
TA = struct([]);
j = 0;
for i = 1:max(ind)
    j = j+1;
    hits = find(ind == i);
    TA{j} = [];
    for k = 1:length(hits)
        TA{j} = [TA{j};T{hits(k)}];
    end
    TA{j} = unique(TA{j},'rows');
end

% elminate double-counting of sequences, form final sequence and
% sequence_times arrays
NDC = eliminate_double_counting_v2(TA,SA,Q.data.converted_array,min_num_reps);     % this step eliminates double counting of sequences
Q.sequences = NDC.S;                                                                % final assignment of sequence information, and transfer to output structure
Q.sequence_times = NDC.T;                                                           % final assignment of sequence timing information and transfer to output structure
Q.sequences_stat.number_sequence = size(NDC.S,1);                                   % total number of unique sequences that were detected

% timing distribution
meanDL = NaN(size(NDC.T,2),1);
sdDL = meanDL;
cvDL = meanDL;
medianDL = meanDL;
iqrDL = meanDL;
meanTL = meanDL;
sdTL = meanDL;
cvTL = meanDL;
medianTL = meanDL;
iqrTL = meanDL;
for i = 1:size(NDC.T,2)
    DL = diff(NDC.T{i},1,2);                % this will yield the time difference between members of the sequence in seconds
    meanDL(i) = mean(DL(:));                % average temporal distances between members of sequence
    sdDL(i) = std(DL(:));                   % standard deviation of temporal distances between recurrences of sequences
    cvDL(i) = sdDL(i)/meanDL(i);            % CV of temporal distances between recurrences of sequences
    medianDL(i) = median(DL(:));            % median temporal distance between recurrences of sequences
    iqrDL(i) = iqr(DL(:));                  % inter-quartile range of temporal distances between recurrences of sequences
    
    TL = diff(NDC.T{1}(:,1));               % temporal separation of start of sequences
    meanTL(i) = mean(TL);
    sdTL(i) = std(TL);
    cvTL(i) = sdTL(i)/meanTL(i);
    medianTL(i) = median(TL);
    iqrTL(i) = iqr(TL);
end

Q.sequences_stat.sequence_event_separation.mean = meanDL;                                 % average temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.sd = sdDL;                                     % standard deviation of temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.cv = cvDL;                                     % CV of temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.median = medianDL;                             % median temporal distance between events within the sequence
Q.sequences_stat.sequence_event_separation.iqr = iqrDL;                                   % inter-quartile range of temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.mean_mean_event_separation = mean(meanDL);           % average across all average temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.mean_sd_event_separation = mean(sdDL);               % average across all standard deviations of temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.mean_cv_event_separation = mean(cvDL);               % average across all CVs of temporal distances between events within the sequence
Q.sequences_stat.sequence_event_separation.median_median_event_separation = median(medianDL);   % median of all median temporal distance between events within the sequence
Q.sequences_stat.sequence_event_separation.median_iqr_event_separation = median(iqrDL);         % median of all inter-quartile ranges of temporal distances between events within the sequence

Q.sequences_stat.sequence_start_separation.mean = meanTL;                                 % average temporal distances between start of sequences
Q.sequences_stat.sequence_start_separation.sd = sdTL;                                     % standard deviation of temporal distances between starts of the sequence
Q.sequences_stat.sequence_start_separation.cv = cvTL;                                     % CV of temporal distances between recurrences of sequences
Q.sequences_stat.sequence_start_separation.median = medianTL;                             % median temporal distance between recurrences of sequences
Q.sequences_stat.sequence_start_separation.iqr = iqrTL;                                   % inter-quartile range of temporal distances between recurrences of sequences
Q.sequences_stat.sequence_start_separation.mean_mean_start_separation = mean(meanTL);           % average across all average temporal distances between recurrences of sequences
Q.sequences_stat.sequence_start_separation.mean_sd_start_separation = mean(sdTL);               % average across all standard deviations of temporal distances between recurrences of sequences
Q.sequences_stat.sequence_start_separation.mean_cv_start_separation = mean(cvTL);               % average across all CVs of temporal distances between recurrences of sequences
Q.sequences_stat.sequence_start_separation.median_median_start_separation = median(medianTL);   % median of all median temporal distance between recurrences of sequences
Q.sequences_stat.sequence_start_separation.median_iqr_start_separation = median(iqrTL);         % median of all inter-quartile ranges of temporal distances between recurrences of sequences

len = zeros(size(NDC.S,1),1);
rep = len;
mean_dur = len;
median_dur = len;
for i = 1:size(NDC.S,1)
    len(i) = find([NDC.S(i,:) 0] ~= 0,1,'last');
    rep(i) = size(NDC.T{i},1);
    dur_i = zeros(size(NDC.T{i},1),1);
    for j = 1:size(NDC.T{i},1)
        dur_i(j) = (NDC.T{i}(j,end)-NDC.T{i}(j,1));
    end
    mean_dur(i) = mean(dur_i);
    median_dur(i) = median(dur_i);
end

Q.sequences_stat.sequence_length.shortest = min(len);                               % shortest detected sequence length (in terms of number of elements in sequence)
Q.sequences_stat.sequence_length.longest = max(len);                                % longest detected sequence length (in terms of number of elements in sequence)
Q.sequences_stat.sequence_length.mean = mean(len);                                  % mean sequence length (in terms of number of element in sequence)
Q.sequences_stat.sequence_length.sd = std(len);                                     % SD of average length
Q.sequences_stat.sequence_length.median = median(len);                              % median length of sequences (in terms of number of elements in sequence)    
Q.sequences_stat.sequence_length.iqr = iqr(len);                                    % inter-quartile range of length of sequences (in terms of number of elements in sequences)

Q.sequences_stat.sequence_repetition.fewest = min(rep);                             % minimal number of repetitions of sequences
Q.sequences_stat.sequence_repetition.most = max(rep);                               % maximal number of repetition of sequences
Q.sequences_stat.sequence_repetition.mean = mean(rep);                              % mean number of repetition of sequences
Q.sequences_stat.sequence_repetition.sd = std(rep);                                 % SD of number of repetition of sequences
Q.sequences_stat.sequence_repetition.median = median(rep);                          % median number of repetition of sequences
Q.sequences_stat.sequence_repetition.iqr = iqr(rep);                                % inter-quartile range of number of repetition of sequences

Q.sequences_stat.sequence_duration.parametric.shortest = min(mean_dur);             % minimal average duration of sequences
Q.sequences_stat.sequence_duration.parametric.longest = max(mean_dur);              % maximal average duration of sequences
Q.sequences_stat.sequence_duration.parametric.mean = mean(mean_dur);                % average of average durations of sequences
Q.sequences_stat.sequence_duration.parametric.sd = std(mean_dur);                   % SD of average durations of sequences
Q.sequences_stat.sequence_duration.non_parametric.shortest = min(median_dur);       % shortest median duration of sequences    
Q.sequences_stat.sequence_duration.non_parametric.longest = max(median_dur);        % longest median duration of sequences    
Q.sequences_stat.sequence_duration.non_parametric.median = median(median_dur);      % median of median durations of sequences
Q.sequences_stat.sequence_duration.non_parametric.iqr = iqr(median_dur);            % inter-quartile range of median durations of sequences

Q.sequences_stat.sequence_index.individual = (len .* rep) / Q.metadata.time_slice;           % index based on INDIVIDUAL sequences: (length * number of repetitions)/time slice length
Q.sequences_stat.sequence_index.global.parametric = Q.sequences_stat.number_sequence*Q.sequences_stat.sequence_length.mean*Q.sequences_stat.sequence_repetition.mean / Q.metadata.time_slice;               % index based on ALL detected sequences (number of sequences * average length of sequences * average number of repetitions)/(average time slice duration) 
Q.sequences_stat.sequence_index.global.non_parametric = Q.sequences_stat.number_sequence*Q.sequences_stat.sequence_length.median*Q.sequences_stat.sequence_repetition.median / Q.metadata.time_slice;     % non_parametric version of previous line

I = calculate_sequence_index_2(Q);

Q.sequences_stat.sequence_index2.individual = I.individual_cells;                   % set of statistics on the number of spikes for each cell that were engaged in sequences
Q.sequences_stat.sequence_index2.global = I.global;                                 % proportion of all spikes (across entire recording session) that were engaged in sequences

% save analysis results if so desired
if save_f                                                                               
    save([fname(1:length(fname)-4) '_seq.mat'],'Q');
end

end

%% Definition of sequences for individual time windows
function R = find_sequences_v25(fname,tc,msl,cd,num_shuffle,ns,min_num_reps,ts,sf)
% This function is a wrapper for the function that defines sequences  
% (find_sequences_2_3_v2). It reads the original data, formats them
% correctly, executes the find_sequences_2_3_v2 function, and assigns the
% results to the output variable R.
% 
% Command line variables:
% fname: name of file that contains the data (uses read_event_data to
% actually read the data, and format them correctly)
%
% tc: offset (in seconds, from each event) that should be evaluated (e.g. 
% stating [0 20] would mean that a time interval from 0 to 20s after each 
% event is evaluated for the next member of a sequence to occur).
%
% cd: closest distance between subsequent the starts (in s) of instances of
% the same sequence. 
%
% num_shuffle: number of statistical shuffles that will be used (the 
% function uses the circshift routine to generate shuffled/shifted data).
%
% ns: percentile score that is being used as an inclusion criterion to 
% count a sequence as accepted. Only positive ns values are defined. All 
% percentiles are expressed as fractions (e.g. 0.95 means that percentiles 
% >95% are accepted. 
%
% Min_num_reps: minimal number of sequence repetitions.
%
% ts: time slice within the data, in seconds (e.g., [100 300] indicates
% that the period from 100s to 300s should be investigated)
%
% sf: is the 'save flag'. Setting it to 1 will save the data to a file with
% similar root name as fname. For this use of the routine, this parameter
% is set to '0' by the calling function.

warning off;

data = read_event_file(fname);              % the original data
num_chan = size(data,2);                    % number of available channels 

% determine the timing of the first and last event in the entire file
te = zeros(num_chan,1);                     % vector of last useable data points for each cell
tb = te;                                    % vector of first useable data points for each cell 
for i = 1:num_chan                          % populate the te and tb vectors
    tb(i) = data(i).time(1);
    te(i) = data(i).time(end);
end
min_time = min(tb);                         % earliest occurrence of an event (across the record)
max_time = max(te);                         % last occurrence of an event (across the record)

% adjust ts boundaries to reflect the realities of the data
if min_time > ts(1)                         
    ts(1) = min_time;
end
if max_time < ts(2)
    ts(2) = max_time;
end

for i = 1:num_chan
    data(i).time = data(i).time(data(i).time <= ts(2)); % chop off the values that are beyond the desired end value
    data(i).value = data(i).value(data(i).time >= ts(1) & data(i).time <= ts(2));
    data(i).time = data(i).time - ts(1);                % chop of the front values, and have the record start at ts(1)
    data(i).time = data(i).time(data(i).time > 0);      % the previous operation can generate negative values.  These are removed.
    data(i).time = ceil(data(i).time * 1000);           % express all data in milliseconds
end

ts = ceil(1000*(ts));                % convert ts into ms.  

% generate array, based on 1 ms conversion, in which '1' values correspond to events
DA = false(num_chan,diff(ts));
for i = 1:num_chan
    DA(i,data(i).time) = true;
end

[R.sequence_times,R.sequences] = find_sequences_2_3_4_5(DA,tc,msl,cd,min_num_reps,num_shuffle,ns);       % the find_sequences_2_3_v2 function identifies actual sequences

% populate remaining components of the output variable R
R.data.original = data;
R.data.converted_array = DA;
R.metadata.command_line.file_name = fname;
R.metadata.command_line.tc = tc/1000;
R.metadata.command_line.shuffles = num_shuffle;
R.metadata.command_line.sign_criterion = ns;
R.metadata.command_line.min_num_repetitions = min_num_reps;
R.metadata.actual_time_slice = ts/1000;

if sf
    save([fname(1:length(fname)-4) '_seq.mat'],'R');
end

end

%% Main sequence detection function
function [F_out,L_out] = find_sequences_2_3_4_5(D,t,sl,sep,min_rep,rep,sco)
% This function detects 2-5 step sequences in the data.  Input 
% parameters:
% 
% sco: statistical cut-off value (e.g., 0.95)
%
% D: input array
%
% t: time restriction window (in seconds, e.g., [0.05 2] would mean that
% members of the sequence are at least 40 ms, and no more than 2 s apart)
% sep: minimal separation of sequences (in seconds)
%
% min_rep: is the minimal number of repetions for a sequence to be detected
% as relevant

% initialize variables
F_2 = struct([]);
L_2 = [];
F_3 = struct([]);
L_3 = [];
F_4 = struct([]);
L_4 = [];
F_5 = struct([]);
L_5 = [];
X = 1:size(D,2);

if sl(sl == 2)
    % **************** 2-step sequences ****************
    
    % generate a list of all possible sequences
    disp('Analyzing 2-step sequences');
    P = nchoosek(1:size(D,1),2);
    L_2 = [P;fliplr(P);[1:size(D,1);1:size(D,1)]'];
    disp([' - Analysis of ' num2str(size(L_2,1)) ' sequence patterns.']);
    
    % ** identify patterns that repeat at least min_rep times in the original data
    for i = 1:size(L_2,1)
        F_2{i} = find_pattern_2_v2(D,L_2(i,:),t,sep,X);   % tests how often a specific pattern occurs
    end
    
    l_2 = zeros(length(F_2),1); % vector that contains the repetition number of individual sequences
    for i = 1:length(F_2)       
        l_2(i) = length(F_2{i});
    end
    
    ind = find(l_2 > min_rep);  % indices (within F_2) which fulfill the minimum-repetition rule
    L_2 = L_2(ind,:);           % sequences that fulfill the minimum-repetition rule
    l_2 = l_2(ind);             % length of sequences that fulfill the minimum-repetition rule
    
    H = struct([]);             % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_2{ind(i)};     % transfer the identified sequence timings to H ...
    end
    F_2 = H;                    % re-define F_2 as a collection of the sequences that occur often enough to be included
    
    % at this point, L_2 contains the relevant patterns, and F_2 the timing of
    % the sequences in L_2.
    
    
    % **** stats for 2-step sequences ****
    
    l_2_s = NaN(rep,size(L_2,1));
    for i = 1:rep
        disp([' - Statistics repetition ' num2str(i)]);
        D_s = shuffle_data(D);                                          % generate the i-th shuffled representation of the data
        for j = 1:size(L_2,1)                                           % go through the relevant patterns (we are only looking at those patterns that were identified as being sufficiently numerous (above))
            l_2_s(i,j) = size(find_pattern_2_v2(D_s,L_2(j,:),t,sep,X),1); % determine the repetition number of the pattern under test (L_2(j,:)) within the shuffled data, with the same t and sep values as used for the original data
        end
    end
    
    % convert each l_2 value into a centile value (measured against the
    % shuffled data)
    l_2_p = NaN(length(l_2),1);
    for i = 1:length(l_2)
        l_2_p(i) = centile_value(l_2(i),l_2_s(:,i));
    end
    
    % test which of the identified centile values are above the statistical
    % cut-off value (sco)
    ind = find(l_2_p > sco);                
    
    L_2 = L_2(ind,:);                                                   % L_2 is restricted to those entires that fulfill the sco criterion
    
    H = struct([]);                                                     % helper structure to contain relevant F_2 values
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_2{ind(i)};
    end
    F_2 = H;                                                            % final assignment of F_2, containing the repetition times of those sequences that fulfill the sco criterion    
end

if sl(sl == 3)
    % ********************* 3-step sequences **************
    % generate a list of all possible sequences
    disp('Analyzing 3-step sequences');
    P = nchoosek(1:size(D,1),3);
    L_3 = [P;fliplr(P);[1:size(D,1);1:size(D,1);1:size(D,1)]'];
    disp([' - Analysis of ' num2str(size(L_3,1)) ' sequence patterns.']);
    
    % ** identify patterns that repeat at least min_rep times in the original data
    % X = 1:size(D(P(1),1:length(D(P(1),:))-2*t(2)-2),2);
    for i = 1:size(L_3,1)
        F_3{i} = find_pattern_3(D,L_3(i,:),t,sep,X);      % tests how often a specific pattern occurs
    end
    
    l_3 = zeros(length(F_3),1);         % vector that contains the repetition number of individual sequences
    for i = 1:length(F_3)
        l_3(i) = length(F_3{i});
    end
    ind = find(l_3 > min_rep);          % indices (within F_3) which fulfill the minimum-repetition rule
    L_3 = L_3(ind,:);                   % sequences that fulfill the minimum-repetition rule
    l_3 = l_3(ind);                     % length of sequences that fulfill the minimum-repetition rule
    
    H = struct([]);                     % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_3{ind(i)};             % transfer the identified sequence timings to H ...
    end
    F_3 = H;                            % re-define F_3 as a collection of the sequences that occur often enough to be included
    
    % at this point, L_3 contains the relevant patterns, and F_3 the timing of
    % the sequences in L_3.
    
    % **** stats for 3-step sequences ****
    
    l_3_s = NaN(rep,size(L_3,1));
    for i = 1:rep
        disp([' - Statistics repetition ' num2str(i)]);
        D_s = shuffle_data(D);          % generate the i-th shuffled representation of the data
        for j = 1:size(L_3,1)           % go through the relevant patterns (we are only looking at those patterns that were identified as being sufficiently numerous (above))
            l_3_s(i,j) = size(find_pattern_3(D_s,L_3(j,:),t,sep,X),1);        % determine the repetition number of the pattern under test (L_3(j,:)) within the shuffled data, with the same t and sep values as used for the original data
        end
    end
    
    % convert each l_3 value into a centile value (measured against the
    % shuffled data)
    l_3_p = NaN(length(l_3),1);         % 
    for i = 1:length(l_3)
        l_3_p(i) = centile_value(l_3(i),l_3_s(:,i));
    end
    
    % test which of the identified centile values are above the statistical
    % cut-off value (sco)
    ind = find(l_3_p > sco);
    
    L_3 = L_3(ind,:);                       % L_3 is restricted to those entires that fulfill the sco criterion
    
    H = struct([]);                         % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_3{ind(i)};                 % transfer the identified sequence timings to H ...
    end
    F_3 = H;                                % final assignment of F_3, containing the repetition times of those sequences that fulfill the sco criterion
end

if sl(sl == 4)
    % ********************* 4-step sequences **************
    % generate a list of all possible sequences
    disp('Analyzing 4-step sequences');
    P = nchoosek(1:size(D,1),4);
    L_4 = [P;fliplr(P);[1:size(D,1);1:size(D,1);1:size(D,1);1:size(D,1)]'];
    disp([' - Analysis of ' num2str(size(L_4,1)) ' sequence patterns.']);
    
    % ** identify patterns that repeat at least min_rep times in the original data
    % X = 1:size(D(P(1),1:length(D(P(1),:))-3*t(2)-3),2);
    for i = 1:size(L_4,1)
        F_4{i} = find_pattern_4(D,L_4(i,:),t,sep,X);      % tests how often a specific pattern occurs
    end
    
    l_4 = zeros(length(F_4),1);         % vector that contains the repetition number of individual sequences
    for i = 1:length(F_4)
        l_4(i) = length(F_4{i});
    end
    ind = find(l_4 > min_rep);          % indices (within F_3) which fulfill the minimum-repetition rule
    L_4 = L_4(ind,:);                   % sequences that fulfill the minimum-repetition rule
    l_4 = l_4(ind);                     % length of sequences that fulfill the minimum-repetition rule
    
    H = struct([]);                     % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_4{ind(i)};             % transfer the identified sequence timings to H ...
    end
    F_4 = H;                            % re-define F_3 as a collection of the sequences that occur often enough to be included
    
    % at this point, L_4 contains the relevant patterns, and F_4 the timing of
    % the sequences in L_4.
    
    % **** stats for 4-step sequences ****
    
    l_4_s = NaN(rep,size(L_4,1));
    for i = 1:rep
        disp([' - Statistics repetition ' num2str(i)]);
        D_s = shuffle_data(D);          % generate the i-th shuffled representation of the data
        for j = 1:size(L_4,1)           % go through the relevant patterns (we are only looking at those patterns that were identified as being sufficiently numerous (above))
            l_4_s(i,j) = size(find_pattern_4(D_s,L_4(j,:),t,sep,X),1);        % determine the repetition number of the pattern under test (L_3(j,:)) within the shuffled data, with the same t and sep values as used for the original data
        end
    end
    
    % convert each l_4 value into a centile value (measured against the
    % shuffled data)
    l_4_p = NaN(length(l_4),1);         % 
    for i = 1:length(l_4)
        l_4_p(i) = centile_value(l_4(i),l_4_s(:,i));
    end
    
    % test which of the identified centile values are above the statistical
    % cut-off value (sco)
    ind = find(l_4_p > sco);
    
    L_4 = L_4(ind,:);                       % L_3 is restricted to those entires that fulfill the sco criterion
    
    H = struct([]);                         % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_4{ind(i)};                 % transfer the identified sequence timings to H ...
    end
    F_4 = H;                                % final assignment of F_3, containing the repetition times of those sequences that fulfill the sco criterion
end

if sl(sl == 5)
    % ********************* 5-step sequences **************
    % generate a list of all possible sequences
    disp('Analyzing 5-step sequences');
    P = nchoosek(1:size(D,1),5);
    L_5 = [P;fliplr(P);[1:size(D,1);1:size(D,1);1:size(D,1);1:size(D,1);1:size(D,1)]'];
    disp([' - Analysis of ' num2str(size(L_5,1)) ' sequence patterns.']);
    
    % ** identify patterns that repeat at least min_rep times in the original data
    % X = 1:size(D(P(1),1:length(D(P(1),:))-4*t(2)-4),2);
    for i = 1:size(L_5,1)
        F_5{i} = find_pattern_5(D,L_5(i,:),t,sep,X);      % tests how often a specific pattern occurs
    end
    
    l_5 = zeros(length(F_5),1);         % vector that contains the repetition number of individual sequences
    for i = 1:length(F_5)
        l_4(i) = length(F_5{i});
    end
    ind = find(l_5 > min_rep);          % indices (within F_3) which fulfill the minimum-repetition rule
    L_5 = L_5(ind,:);                   % sequences that fulfill the minimum-repetition rule
    l_5 = l_5(ind);                     % length of sequences that fulfill the minimum-repetition rule
    
    H = struct([]);                     % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_5{ind(i)};             % transfer the identified sequence timings to H ...
    end
    F_5 = H;                            % re-define F_3 as a collection of the sequences that occur often enough to be included
    
    % at this point, L_5 contains the relevant patterns, and F_5 the timing of
    % the sequences in L_5.
    
    % **** stats for 5-step sequences ****
    
    l_5_s = NaN(rep,size(L_5,1));
    for i = 1:rep
        disp([' - Statistics repetition ' num2str(i)]);
        D_s = shuffle_data(D);          % generate the i-th shuffled representation of the data
        for j = 1:size(L_5,1)           % go through the relevant patterns (we are only looking at those patterns that were identified as being sufficiently numerous (above))
            l_5_s(i,j) = size(find_pattern_5(D_s,L_5(j,:),t,sep,X),1);        % determine the repetition number of the pattern under test (L_3(j,:)) within the shuffled data, with the same t and sep values as used for the original data
        end
    end
    
    % convert each l_5 value into a centile value (measured against the
    % shuffled data)
    l_5_p = NaN(length(l_5),1);         % 
    for i = 1:length(l_5)
        l_5_p(i) = centile_value(l_5(i),l_5_s(:,i));
    end
    
    % test which of the identified centile values are above the statistical
    % cut-off value (sco)
    ind = find(l_5_p > sco);
    
    L_5 = L_5(ind,:);                       % L_3 is restricted to those entires that fulfill the sco criterion
    
    H = struct([]);                         % helper structure to contain the occurrence timing of the relevant sequences
    j = 0;
    for i = 1:length(ind)
        j = j+1;
        H{j} = F_5{ind(i)};                 % transfer the identified sequence timings to H ...
    end
    F_5 = H;                                % final assignment of F_3, containing the repetition times of those sequences that fulfill the sco criterion
end
    
% **** Combine 2-5 step sequence analysis results
if ~isempty(F_2)
    F_out = [F_2 F_3 F_4 F_5];
elseif ~isempty(F_3)
    F_out = [F_3 F_4 F_5];
elseif ~isempty(F_4)
    F_out = [F_4 F_5];
else
    F_out = F_5;
end
L_out = {L_2 L_3 L_4 L_5};
L_out = L_out(~cellfun(@isempty,L_out));

end

%% function to find 3-step patterns
function ST = find_pattern_3(D,P,t,sep,X)
% This function checks whether and how often a specific pattern P occurs
% in the data array D, using the time window t and the shortest 
% separation parameter sep.  Command line parameters:
%
% D: data array (cells x time (in ms))
%
% P: test pattern (e.g. [1 2 4] means that cell activity 1 is followed by 
% cell activity 2, and then 4)
%
% t:time window of occurrence (e.g., [0.05 2] means that the separation 
% between events that are members of the sequence is between 50 ms and 
% 2s.
%
% sep: minimal separation between sequences (in s)

% convert t and sep into ms values
t = round(t*1000);
sep = sep*1000;

m = 0;
hit1 = X(D(P(1),1:length(D(P(1),:))-2*t(2)-2));                                 % identify all occurrences of the first member of the pattern (P(1)) within the corresponding data stream (D(P(1),:)) that may qualify.  t(2)*2-2 is subtracted because no event can qualify that does not leave room for t(2)*2-2 milliseconds until the end of the record
sequence_time = NaN(length(hit1),3);                                            % initialize sequence_time array (NaNs) - each row of the array will contain one hit1 entry, and corresponding second and third events (if any)

for i = 1:length(hit1)                                                          % for all hit1 values ...
    hit2 = X(D(P(2),hit1(i)+t(1):hit1(i)+t(2)));                                % check whether there the second member of the sequence pattern (P(2)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit1(i)+t(1))
    if ~isempty(hit2)                                                           % if there were any hit2 values ...
        for j = 1:length(hit2)                                                  % for all hit2 values
            hit2(j) = hit2(j) + hit1(i) + t(1) - 1;                             % correct the hit2 values 
            hit3 = X(D(P(3),hit2(j) + t(1):hit2(j) + t(2)));                    % check whether there the third member of the sequence pattern (P(3)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit2(i)+t(1))
            if ~isempty(hit3)                                                   % if there was a hit3 event ...
                hit3 = hit3(end) + hit2(j) + t(1) - 1;                          % correct the timing
                m = m+1;                                                        % increment counter of valid sequences    
                sequence_time(m,:) = [hit1(i) hit2(j) hit3];                    % populate the sequence_time array with the identified values
                break;                                                          % avoids adding multiple instances of a sequence starting from the same root (hit1)
            end
        end
    end
end

ST = [];                                                        % ST is the output structure, containing the timing of the times the sequence in question was identified
if m > 0                                                        % if three step sequences were found ...
    ST = NaN(m,3);                                              % ST is re-initialized to an NaN array    
    n = 1;                                                      % valid sequence counter
    ST(1,:) = sequence_time(1,:);                               % the first entry in the array will always be the first occurrence of the sequence    
    for i = 2:m
        if sequence_time(i,1)-sequence_time(i-1,1) >= sep       % if subsequent entries of sequence_time are sufficiently separated from one another ...
            n = n+1;                                            % increment valid sequence counter
            ST(n,:) = sequence_time(i,:);                       % and populate output array
        end
    end
    ST = ST(1:n,:);                                             % restrict output array to only those entries that are valid (1:n)
end

ST = ST/1000;                                                   % convert ST to seconds

end

%% function to find 4-step patterns
function ST = find_pattern_4(D,P,t,sep,X)
% This function checks whether and how often a specific pattern P occurs
% in the data array D, using the time window t and the shortest 
% separation parameter sep.  Command line parameters:
%
% D: data array (cells x time (in ms))
%
% P: test pattern (e.g. [1 2 4 3] means that cell activity 1 is followed by 
% cell activity 2, then 4, then 3)
%
% t:time window of occurrence (e.g., [0.05 2] means that the separation 
% between events that are members of the sequence is between 50 ms and 
% 2s.
%
% sep: minimal separation between sequences (in s)

% convert t and sep into ms values
t = round(t*1000);
sep = sep*1000;

m = 0;
hit1 = X(D(P(1),1:length(D(P(1),:))-3*t(2)-3));                                 % identify all occurrences of the first member of the pattern (P(1)) within the corresponding data stream (D(P(1),:)) that may qualify.  t(2)*2-2 is subtracted because no event can qualify that does not leave room for t(2)*2-2 milliseconds until the end of the record
sequence_time = NaN(length(hit1),4);                                            % initialize sequence_time array (NaNs) - each row of the array will contain one hit1 entry, and corresponding second and third events (if any)

for i = 1:length(hit1)                                                          % for all hit1 values ...
    hit2 = X(D(P(2),hit1(i)+t(1):hit1(i)+t(2)));                                % check whether there the second member of the sequence pattern (P(2)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit1(i)+t(1))
    if ~isempty(hit2)                                                           % if there were any hit2 values ...
        for j = 1:length(hit2)                                                  % for each of the identified hit2 values    
            hit2(j) = hit2(j) + hit1(i) + t(1) - 1;                             % correct the hit2 value
            hit3 = X(D(P(3),hit2(j) + t(1):hit2(j) + t(2)));                    % check whether there the third member of the sequence pattern (P(3)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit2(i)+t(1))
            if ~isempty(hit3)                                                   % if there was a hit3 event
                for k = 1:length(hit3)                                          % for all hit3 events ...    
                    hit3(k) = hit3(k) + hit2(j) + t(1) - 1;                     % correct the hit3 timing
                    hit4 = X(D(P(4),hit3(k) + t(1):hit3(k) + t(2)));            % check whether there the fourth member of the sequence pattern (P(4)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit3(i)+t(1))    
                    if ~isempty(hit4)                                           % if there was a hit4 event ...
                        hit4 = hit4(end) + hit3(k) + t(1) - 1;                  % correct its timing
                        m = m+1;                                                % increment counter of valid sequences    
                        sequence_time(m,:) = [hit1(i) hit2(j) hit3(k) hit4];    % populate the sequence_time array with the identified values
                        break;                                                  % to avoid double counting
                    end
                end
            end
        end
    end
end

ST = [];                                                        % ST is the output structure, containing the timing of the times the sequence in question was identified
if m > 0                                                        % if four step sequences were found ...
    ST = NaN(m,4);                                              % ST is re-initialized to an NaN array    
    n = 1;                                                      % valid sequence counter
    ST(1,:) = sequence_time(1,:);                               % the first entry in the array will always be the first occurrence of the sequence    
    for i = 2:m
        if sequence_time(i,1)-sequence_time(i-1,1) >= sep       % if subsequent entries of sequence_time are sufficiently separated from one another ...
            n = n+1;                                            % increment valid sequence counter
            ST(n,:) = sequence_time(i,:);                       % and populate output array
        end
    end
    ST = ST(1:n,:);                                             % restrict output array to only those entries that are valid (1:n)
end

ST = ST/1000;                                                   % convert ST to seconds

end

%% function to find 5-step patterns
function ST = find_pattern_5(D,P,t,sep,X)
% This function checks whether and how often a specific pattern P occurs
% in the data array D, using the time window t and the shortest 
% separation parameter sep.  Command line parameters:
%
% D: data array (cells x time (in ms))
%
% P: test pattern (e.g. [1 2 4 3 7] means that cell activity 1 is followed by 
% cell activity 2, then 4, then 3, and then 7)
%
% t:time window of occurrence (e.g., [0.05 2] means that the separation 
% between events that are members of the sequence is between 50 ms and 
% 2s.
%
% sep: minimal separation between sequences (in s)

% convert t and sep into ms values
t = round(t*1000);
sep = sep*1000;

m = 0;
hit1 = X(D(P(1),1:length(D(P(1),:))-4*t(2)-4));                                 % identify all occurrences of the first member of the pattern (P(1)) within the corresponding data stream (D(P(1),:)) that may qualify.  t(2)*2-2 is subtracted because no event can qualify that does not leave room for t(2)*2-2 milliseconds until the end of the record
sequence_time = NaN(length(hit1),5);                                            % initialize sequence_time array (NaNs) - each row of the array will contain one hit1 entry, and corresponding second and third events (if any)

for i = 1:length(hit1)                                                          % for all hit1 values ...
    hit2 = X(D(P(2),hit1(i)+t(1):hit1(i)+t(2)));                                % check whether there is a second member of the sequence pattern (P(2)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit1(i)+t(1))
    if ~isempty(hit2)                                                           % if there were any hit2 values ...
        for j = 1:length(hit2)                                                  % for each of the identified hit2 values    
            hit2(j) = hit2(j) + hit1(i) + t(1) - 1;                             % correct its timing
            hit3 = X(D(P(3),hit2(j) + t(1):hit2(j) + t(2)));                    % check whether there is a third member of the sequence pattern (P(3)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit2(i)+t(1))
            if ~isempty(hit3)                                                   % if there was a hit3 event
                for k = 1:length(hit3)                                          % for each hit 3 events ...    
                    hit3(k) = hit3(k) + hit2(j) + t(1) - 1;                     % correct its timing
                    hit4 = X(D(P(4),hit3(k) + t(1):hit3(k) + t(2)));            % check whether there is a fourth member of the sequence pattern (P(4)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit3(i)+t(1))    
                    if ~isempty(hit4)                                           % if there was a hit4 event ...
                        for l = 1:length(hit4)                                  % for each hit4 event
                            hit4(l) = hit4(l) + hit3(k) + t(1) - 1;             % correct its timing
                            hit5 = X(D(P(5),hit4(l) + t(1):hit4(l) + t(2)));    % check whether there is a fifth member of the sequence pattern (P(4)) is present in the window between t(1) and t(2) after that event.  Pick the last of these events, and determine the actual time within the record (add hit3(i)+t(1))        
                            if ~isempty(hit5)                                   % if there is ia hit5 event    
                                hit5 = hit5(end) + hit4(l) + t(1) - 1;          % correct its timing
                                m = m+1;                                        % increment counter of valid sequences    
                                sequence_time(m,:) = [hit1(i) hit2(j) hit3(k) hit4(l) hit5];     % populate the sequence_time array with the identified values
                                break;                                          % avoid double counting
                            end
                        end
                    end
                end
            end
        end
    end
end

ST = [];                                                        % ST is the output structure, containing the timing of the times the sequence in question was identified
if m > 0                                                        % if four step sequences were found ...
    ST = NaN(m,5);                                              % ST is re-initialized to an NaN array    
    n = 1;                                                      % valid sequence counter
    ST(1,:) = sequence_time(1,:);                               % the first entry in the array will always be the first occurrence of the sequence    
    for i = 2:m
        if sequence_time(i,1)-sequence_time(i-1,1) >= sep       % if subsequent entries of sequence_time are sufficiently separated from one another ...
            n = n+1;                                            % increment valid sequence counter
            ST(n,:) = sequence_time(i,:);                       % and populate output array
        end
    end
    ST = ST(1:n,:);                                             % restrict output array to only those entries that are valid (1:n)
end

ST = ST/1000;                                                   % convert ST to seconds

end

%% function to find 2-step patterns
function ST = find_pattern_2_v2(D,P,t,sep,X)
% This function checks whether and how often a specific pattern P occurs
% in the data array D, using the time window t and the shortest 
% separation parameter sep.  Command line parameters:
%
% D: data array (cells x time (in ms))
%
% P: test pattern (e.g. [1 2] means that cell activity 1 is followed by 
% cell activity 2)
%
% t:time window of occurrence (e.g., [0.05 2] means that the separation 
% between events that are members of the sequence is between 50 ms and 
% 2s.
%
% sep: minimal separation between sequences (in s)

% convert t and sep into ms values
t = round(t*1000);              
sep = sep*1000;

% find pattern occurrences
hit1 = X(D(P(1),1:length(D(P(1),:))-t(2)) == 1);            % identify all occurrences of the first member of the pattern (P(1)) within the corresponding data stream (D(P(1),:)) that may qualify.  t(2) is subtracted because no event can qualify that does not leave room for t(2) milliseconds until the end of the record
sequence_time = NaN(length(hit1),2);                        % initialize sequence_time array (NaNs) - each row of the array will contain one hit1 entry, and a corresponding second event (if any)
sequence_time(:,1) = hit1;                                  % populate the first member of each row with hit 1 (note - hit1 is an index in the data array D. Because D is a series of 1s and 0s with 1ms separation, the indices correspond to times (in ms))
for i = 1:length(hit1)                                      % for all hit1 values ...
    hit2 = X(D(P(2),hit1(i)+t(1):hit1(i)+t(2)));
    if hit2                                                 % if something was found ...
        sequence_time(i,2) = hit1(i)+t(1)-1 + hit2(end);    % populate the second member of the sequence_time array
    end
end
sequence_time = sequence_time(~isnan(sequence_time(:,2)),:);    % restrict the sequence_time array to only those entries where both entries were valid

ST = [];                                                    % ST is the output structure, containing the timing of the times the sequence in question was identified
if ~isempty(sequence_time)                                  % if there are any entries ...
    ST = [sequence_time(1,:); sequence_time];               % an array is generated that contains the first line twice (so that we can utilize the diff function in the next step)
    ST = [sequence_time(1,:); sequence_time(diff(ST(:,1)) >= sep,:)];   % calculate time difference between successive occurrences of the sequence (diff(ST(:,1)), and make sure that they are at least sep ms apart
end

ST = ST/1000;                                               % convert ST into seconds

end

%% Calculate centiles
function p = centile_value(v,A)
% this generates centile values (actually fractions, to reduce the
% computational load (e.g., 0.67 corresponds to 67%)

p = (sum(A < v) + 0.5*sum(A == v)) / length(A);
end

%% Shuffle data
function D_s = shuffle_data(D)
% This function generates shuffled data, using a circshift mechanism (by a
% random number of positions within the original data.  All rows of
% input array D are circ-shifted by a random number of positions

D_s = false(size(D));
for j = 1:size(D,1)
        D_s(j,:) = circshift(D(j,:),randi(length(D(j,:))));
end

end

%% read event data
function data = read_event_file(fname)
% This is a helper function used to read data generated by the Inscopix
% routine that produces deconvoluted ('spike') data from calcium imaging
% traces.  fname is the name of the Inscopix data file (this is a csv 
% file).

% read original data
B = table2struct(readtable(fname));     % read input file into structure

% transfer variables from the unwieldy structure B to more convenient
% variables timeB, valueB and chanB.  An event in chanB(i) at timeB(i) has
% an amplitude of valueB(i).
timeB = NaN(size(B,1),1);
valueB = timeB;
chanB = timeB;
for i = 1:size(B,1)
    timeB(i) = B(i).Time_s_;
    valueB(i) = B(i).Value;
    chanB(i) = str2num(B(i).CellName(2:end));
end

% sort them and generate output structure
UniqueCellNumbers = unique(chanB);          % identify unique entries into chanB                        
num_cells = length(UniqueCellNumbers);      % convenience value, measuring the number of cells in input array
for i = 1:num_cells                         % for all cells ...
    data(i).chan = UniqueCellNumbers(i);    % generate a look-up table, data(i).chan contains cell numbers in the original data array
    data(i).time = timeB(chanB == data(i).chan);    % data(i).time contains the corresponding timeB 
    data(i).value = valueB(chanB == data(i).chan);  % data(i).value contains the corresponding amplitude values
end

end

%% remove double counted entries
function NDC = eliminate_double_counting_v2(T,S,DA,num_rep)
% This routine identifies event sequences that are entirely contained in 
% other identified sequences (for example a two step sequence [e.g., 2 5], with 
% each member of that sequence being also part of a three step sequence 
% [e.g., 7 2 5]).  The shorter of such double-counted sequences is removed.
% If a short sequence is partly overlapping with a longer one, but can also 
% occur independently, the function re-checks whether the independent
% occurrences occur often enough to qualify for a standalone sequence
% designation.
%
% Command line parameters:
%
% T: times of sequence occurrences (in s) 
%
% S: array of sequences (zero-padded)
% 
% DA: input data array (as a string of 1s and 0s) for each channel,
% denoting ms steps
%
% num_rep: minimal number a given sequence must be replicated 

% determine length of sequences and generate processing order (descending length of sequences)
len = zeros(size(T,2),1);
for i = 1:size(T,2)
    len(i) = find([S(i,:) 0] ~= 0,1,'last');    % find the last non-zero entry
end
[~,ind] = sort(len,'descend');                  % sort sequences by length (ind is the sequence of index entries in the S (or T) array)

% re-generate ind, to be in order of the length of the sequence, and, within
% a given length, in order of the number of repetitions
so = zeros(size(len));                          % sort order vector
j = 0;                                          % running index within sort order vector
for i = max(len):-1:2                           % go backward through the lengths of len (starting with the max)    
    h = find(len(ind) == i);                    % find the entries in the len(ind) vector that have the length i     
    len1 = zeros(length(h),1);                  % helper variable
    for k = 1:length(h)                         % for each of the entries (k) within len(ind) that have the length i ...
        len1(k) = size(T{ind(h(k))},1);         % set len1(k) to the corresponding number of repetitions of the sequence
    end
    [~,ind2] = sort(len1,'descend');            % ind2 is the sort order within len1 of the sequences by descending numbers of repetitions
    so(j+1:j+length(h)) = h(ind2);              % add elements to the sort order vector in the order of sequence repetitions
    j = j+length(h);                            % update the running index within the sort order vector
end
ind = ind(so);                                  % update the order within ind (note that the actual number within ind are still referring to indices within T and S).

if ~isempty(ind)
    for i = 1:length(ind)          % for all sequences in descending order of length and recurrence rates ...
        for j = 1:len(ind(i))      % for all individual member of the sequence ...    
            valid_time = ones(size(T{ind(i)}(:,j),1),1);                    % helper variable that refers to recurrence times within T
            if ~isempty(T{ind(i)}(:,j))                                     % should never be empty, but just in case ...    
                for k = 1:size(T{ind(i)}(:,j),1)                            % for all entries into the relevant T entry
                    % the following steps will identify events that are part of
                    % sequences to '2' and label times that are already identified as part of a
                    % longer sequences as invalid (valid_time is set to 0
                    % for such events)
                    try    
                    if DA(S(ind(i),j),round(T{ind(i)}(k,j)*1000)) == 2
                        valid_time(k) = 0;
                    else
                        DA(S(ind(i),j),round(T{ind(i)}(k,j)*1000)) = 2;
                    end
                    catch
                    end
                end
            end
            T{ind(i)} = T{ind(i)}(valid_time == 1,:);       % we keep only those time entries that are valid
        end
    end
end

% final generation of output. NDC.S are sequences, NDC.T are corresponding
% occurrences
j = 0;
NDC.S = [];
NDC.T = struct([]);
% the following step tests whether the valid sequences occur often enough
% to be counted (if their number is greater than num_rep)
if ~isempty(S)
    for i = 1:size(S,1)
        if size(T{i},1) >= num_rep  % if there are sufficient occurrences of the sequence ...
            j = j+1;                % increment the sequence counter
            NDC.S(j,:) = S(i,:);    % assign the sequence to NDC.S
            NDC.T{j} = T{i};        % assign the sequence occurrences to NDC
        end
    end
end

end

%% calculate sequence index 2 
function I = calculate_sequence_index_2(Q)
% This function generates statistics on the proportion of spikes of
% individual cells that were engaged in sequences (either on a per-cell
% basis, across cells, or as a global parameter for all spikes of that
% recording.

nsis = zeros(size(Q.data.converted_array,1),1);             % a vector where each entry represents one cell 
num_events = nsis;                                          % another vector of the same size as nsis   
for i = 1:size(Q.sequences,1)                               % for all identified sequence entries (which are in the form of an array that is padded with zeros)
    h = find([Q.sequences(i,:) 0] ~= 0,1,'last');           % find the true sequence length 
    for j = 1:h                                             % for all members of the sequence
       nsis(Q.sequences(i,j)) = nsis(Q.sequences(i,j)) + size(Q.sequence_times{i},1);   % for each cell identify in how many repetitions of sequences it was involved
    end
end
for i = 1:length(num_events)                                % for all cells ...
    num_events(i) = size(Q.data.original(i).time,1);        % log the total number of events that were identified
end
I.individual_cells.proportion = nsis ./ num_events;         % I.individual_cells is the proportion of events of a given cell that were part of sequences
I.individual_cells.average = mean(I.individual_cells.proportion);      % Average proportion of events of a given cell that were part of sequences
I.individual_cells.SD = std(I.individual_cells.proportion);            % SD of proportion of events of a given cell that were part of sequences
I.individual_cells.median = median(I.individual_cells.proportion);     % median proportion of events of a given cell that were part of sequences
I.individual_cells.iqr = iqr(I.individual_cells.proportion);           % inter-quartile range of proportion of events of a given cell that were part of sequences
I.global = sum(nsis)/sum(num_events);                       % I.global is the a global parameter, describing how many spikes (out of all spikes) were involved in sequences

end